In [618]:
import random
x=random.randint(1,100)
print(x)

42


In [619]:
x=random.randint(1,100)

In [620]:
print(x)

51


In [621]:
import numpy as np
x=np.array(100)
print(x)

100


CELDAS DE TEXTO
Esta celda es de Texto

In [623]:
import numpy as np
escalar=np.array(10)
vector=np.array([1,3,5,7,9])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
tensor=np.array([[[1,2],[3,4],[5,6]]])

In [624]:
print(escalar)
print(vector)
print(matrix)
print(tensor)

10
[1 3 5 7 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]
  [5 6]]]


In [625]:
tensor=np.array([
    [[[1,2],[3,4],[5,6]]],
	[[[1,2],[3,4],[5,6]]],
	[[[1,2],[3,4],[5,6]]]
])

tensor

array([[[[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]]]])

In [626]:
print(tensor)

[[[[1 2]
   [3 4]
   [5 6]]]


 [[[1 2]
   [3 4]
   [5 6]]]


 [[[1 2]
   [3 4]
   [5 6]]]]


In [627]:
ceros=np.zeros((3,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [628]:
unos=np.ones((4,4))
unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [629]:
v1=np.arange(9)
v1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [630]:
v2=np.arange(10,100)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [631]:
v3=np.arange(10,100,10)
v3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [632]:
import random
lista=[random.randint(1,100) for i in range(random.randint(5,15))]
lista


[29, 67, 40, 54, 37, 69, 14, 2]

In [633]:
vector=np.array(lista)
vector

array([29, 67, 40, 54, 37, 69, 14,  2])

In [634]:
x=random.random()
x=int(x*100)
x

8

In [635]:
#tam=int(input("ingrese cantidad"))
vec=np.random.randint(1,100,size=(1,random.randint(5,15)))
vec

array([[32, 73, 13, 85, 33, 42, 11]])

In [636]:
arreglo=np.arange(6)
nuevo=arreglo.reshape(3,2)
nuevo

array([[0, 1],
       [2, 3],
       [4, 5]])

In [637]:
arreglo=np.arange(6)
arreglo=np.append(arreglo,22)
arreglo

array([ 0,  1,  2,  3,  4,  5, 22])

In [638]:
print(arreglo.size)

7


In [639]:
lista=[random.randint(1,100) for i in range(random.randint(5,15))]
lista
npvec=np.array(lista)
npvec



array([11, 83, 98,  5, 84, 53, 15])

In [640]:
npvec[:int(npvec.size/2):3]

array([11])

In [641]:
npvec[int(npvec.size/2)::2]

array([ 5, 53])

In [642]:
lista[::2]

[11, 98, 84, 15]

In [643]:
lista[8:]

[]

In [644]:
lista[-1:-5:-1]

[15, 53, 84, 5]

In [645]:
matrix=np.random.randint(1,100,size=(5,5))
matrix

array([[33, 61, 52, 55, 75],
       [ 8,  2, 39, 93, 51],
       [95, 76, 53, 68, 18],
       [63, 79, 71, 10, 65],
       [75, 11, 79, 28, 75]])

In [646]:
matrix[:,1::2]

array([[61, 55],
       [ 2, 93],
       [76, 68],
       [79, 10],
       [11, 28]])

In [647]:
np.mean(matrix[0])

55.2

In [648]:
import csv
import numpy as np
arreglo=np.array([])
type(arreglo)
#with open("C:\\Users\\usuario\\Dropbox\\sena2025\\Trimestre1-Febrero10-Abril25\\2996881_Analitica\\datos2.csv") as mycsv:
with open("employees.csv") as mycsv:
    data=csv.reader(mycsv)
    print(data)
    print(type(data))
    for x in data:
        #print(x)
        arreglo=np.append(arreglo,x)
print(arreglo.shape)
print(arreglo.ndim)
arreglo=arreglo.reshape(51,11)
salario = arreglo[1:,7:8]
salarionum= salario.astype(int)

print(salarionum)

print("suma de los salarios:  ", np.sum(salarionum))
print("promedio de los salarios:  ", np.mean(salarionum))
print("salario menor: ",np.min(salarionum))
print("salario maximo: ",np.max(salarionum))






<class '_csv.reader'>
(561,)
1
[[ 2600]
 [ 2600]
 [ 4400]
 [13000]
 [ 6000]
 [ 6500]
 [10000]
 [12008]
 [ 8300]
 [24000]
 [17000]
 [17000]
 [ 9000]
 [ 6000]
 [ 4800]
 [ 4800]
 [ 4200]
 [12008]
 [ 9000]
 [ 8200]
 [ 7700]
 [ 7800]
 [ 6900]
 [11000]
 [ 3100]
 [ 2900]
 [ 2800]
 [ 2600]
 [ 2500]
 [ 8000]
 [ 8200]
 [ 7900]
 [ 6500]
 [ 5800]
 [ 3200]
 [ 2700]
 [ 2400]
 [ 2200]
 [ 3300]
 [ 2800]
 [ 2500]
 [ 2100]
 [ 3300]
 [ 2900]
 [ 2400]
 [ 2200]
 [ 3600]
 [ 3200]
 [ 2700]
 [ 2500]]
suma de los salarios:   309116
promedio de los salarios:   6182.32
salario menor:  2100
salario maximo:  24000


In [649]:
nombres= arreglo[1:,2:3]
nombres
#apellidos= arreglo[1:,3:4]


array([['OConnell'],
       ['Grant'],
       ['Whalen'],
       ['Hartstein'],
       ['Fay'],
       ['Mavris'],
       ['Baer'],
       ['Higgins'],
       ['Gietz'],
       ['King'],
       ['Kochhar'],
       ['De Haan'],
       ['Hunold'],
       ['Ernst'],
       ['Austin'],
       ['Pataballa'],
       ['Lorentz'],
       ['Greenberg'],
       ['Faviet'],
       ['Chen'],
       ['Sciarra'],
       ['Urman'],
       ['Popp'],
       ['Raphaely'],
       ['Khoo'],
       ['Baida'],
       ['Tobias'],
       ['Himuro'],
       ['Colmenares'],
       ['Weiss'],
       ['Fripp'],
       ['Kaufling'],
       ['Vollman'],
       ['Mourgos'],
       ['Nayer'],
       ['Mikkilineni'],
       ['Landry'],
       ['Markle'],
       ['Bissot'],
       ['Atkinson'],
       ['Marlow'],
       ['Olson'],
       ['Mallin'],
       ['Rogers'],
       ['Gee'],
       ['Philtanker'],
       ['Ladwig'],
       ['Stiles'],
       ['Seo'],
       ['Patel']], dtype='<U32')