In [ ]:
import numpy as np
matrix=np.array([
            [[1,2,3],[4,5,6]]],
            [[[6,7,8],[2,3,5]]],
            [[[6,9,3]]
            ])
print(matrix)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
ceros=np.zeros((3,3))

In [ ]:
v1=np.arange(9)
v1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
v2=np.arange(10,100)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
v3=np.arange(10,100,10)
v3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
import random
lista=[random.randint(1,100) for i in range(random.randint(5,15))]
lista

[56, 57, 29, 66, 44, 10, 70, 66, 86, 87, 81]

In [ ]:
vector=np.array(lista)
vector

array([ 57,   8,  67,  59,  36,  26,  69,  21,  57,  91, 100])

In [ ]:
vec=np.random.randint(1,100,size=(1,random.randint(5,15)))
vec

array([[10, 49, 59, 54, 72, 62, 39, 51,  6]])

In [ ]:
arreglo=np.arange(10)
can=int(input("ingrese un numero: " ))
nuevo=arreglo.reshape((5*2))
if can<arreglo:
  can=np.append(can==10)
else:
  print("la cantidad supera el rango, el rango es hasta 10")
print(nuevo)
print(arreglo.size)

ingrese un numero:  7


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
matrix=np.random.randint(1,100,size=(5,5))
npvec=np.array(matrix)
matrix
matrix[ : , int(npvec.size/2): ]
matrix



array([[22, 48, 21, 46,  8],
       [82, 66, 16, 87, 50],
       [47, 75, 34, 75, 75],
       [ 7, 48, 74, 56, 58],
       [26, 42, 84, 28, 96]])